import { existsSync, readdirSync, readFileSync } from 'node:fs';
import { join, extname } from 'node:path';
import { discoverLayout, listFiles } from '../utils/fs.js';
import { ID_PREFIXES, GEOJSON_FILE_NAMES, GLOBAL_ONLY_TABLES } from '../schema/registry.js';

// Tables where the GeoJSON file is optional:
// - opening: wall-mode is CSV-only, slab-mode has geometry
// - space: boundary auto-generated by build
// - stair/ramp/railing: sketch/run-based; a single LineString rarely represents them,
//   so geometry falls back to an optional GLB mesh (mesh_file)
const OPTIONAL_GEOMETRY_TABLES = new Set(['opening', 'space', 'stair', 'ramp', 'railing']);

const KNOWN_CSV_NAMES = new Set(Object.keys(ID_PREFIXES).map((t) => `${t}.csv`));
const KNOWN_GEOJSON_NAMES = new Set(Object.values(GEOJSON_FILE_NAMES).map((s) => `${s}.geojson`));
const KNOWN_GLOBAL_EXTRAS = new Set(['_IdMap.csv']);

const CURRENT_FORMAT_VERSION = 2;

export function validateStructure(dir: string): string[] {
  const issues: string[] = [];
  const layout = discoverLayout(dir);

  // Must have global/
  if (!existsSync(layout.globalDir)) {
    issues.push('global/  missing global/ directory');
    return issues;
  }

  // global/ must have level.csv. grid.csv is optional — a structural grid is
  // meaningful for column layouts but pointless for plain architectural/MEP models.
  const globalFiles = listFiles(layout.globalDir);
  if (!globalFiles.includes('level.csv')) {
    issues.push('global/  missing level.csv');
  }

  // global/ — CSVs and GeoJSON files (cross-floor elements may have geometry in global/) allowed
  for (const f of globalFiles) {
    const ext = extname(f);
    if (ext === '.svg') {
      issues.push(`global/${f}  SVG files are not allowed (use GeoJSON; see migration script)`);
    } else if (ext === '.csv') {
      if (!KNOWN_CSV_NAMES.has(f) && !KNOWN_GLOBAL_EXTRAS.has(f)) {
        issues.push(`global/${f}  unknown file — only known table CSVs are allowed`);
      }
    } else if (ext === '.geojson') {
      if (!KNOWN_GEOJSON_NAMES.has(f)) {
        issues.push(`global/${f}  unknown GeoJSON file — not a recognized BimDown table name`);
      }
    } else {
      issues.push(`global/${f}  unexpected file — only CSV and GeoJSON files are allowed in global/`);
    }
  }

  // Level dirs
  for (const ld of layout.levelDirs) {
    if (!/^lv-.+$/.test(ld.name)) {
      issues.push(`${ld.name}/  directory name does not match lv-{id} pattern`);
      continue;
    }

    const files = listFiles(ld.path);

    for (const f of files) {
      const ext = extname(f);
      if (ext === '.csv') {
        if (!KNOWN_CSV_NAMES.has(f)) {
          issues.push(`${ld.name}/${f}  unknown file — not a recognized BimDown table`);
        }
        const tableName = f.replace('.csv', '');
        if (GLOBAL_ONLY_TABLES.has(tableName)) {
          issues.push(`${ld.name}/${f}  ${tableName} belongs in global/ only`);
        }
      } else if (ext === '.svg') {
        issues.push(`${ld.name}/${f}  SVG files are not allowed (use GeoJSON; see migration script)`);
      } else if (ext === '.geojson') {
        if (!KNOWN_GEOJSON_NAMES.has(f)) {
          issues.push(`${ld.name}/${f}  unknown GeoJSON file — not a recognized BimDown table name`);
        }
        const base = f.replace('.geojson', '');
        const tableName = Object.entries(GEOJSON_FILE_NAMES).find(([, v]) => v === base)?.[0];
        if (tableName && !files.includes(`${tableName}.csv`)) {
          issues.push(`${ld.name}/${f}  orphaned GeoJSON — no matching ${tableName}.csv`);
        }
      } else {
        issues.push(`${ld.name}/${f}  unexpected file — only CSV and GeoJSON files are allowed`);
      }
    }

    // CSV must have matching GeoJSON (reverse check) — unless geometry is optional for that table
    for (const f of files) {
      if (extname(f) !== '.csv') continue;
      const tableName = f.replace('.csv', '');
      const geojsonName = GEOJSON_FILE_NAMES[tableName];
      if (geojsonName && !files.includes(`${geojsonName}.geojson`) && !OPTIONAL_GEOMETRY_TABLES.has(tableName)) {
        issues.push(`${ld.name}/${f}  missing paired GeoJSON file "${geojsonName}.geojson"`);
      }
    }
  }

  // Reject top-level entries other than global/, lv-{n}/, project_metadata.json,
  // _IdMap.csv (UUID↔short-id map) and mesh/ (GLB asset directory).
  const topEntries = readdirSync(dir);
  for (const f of topEntries) {
    if (f === 'global' || /^lv-.+$/.test(f)) continue;
    if (f === 'project_metadata.json') continue;
    if (f === '_IdMap.csv' || f === 'mesh') continue;
    if (f.startsWith('.')) continue;
    issues.push(`${f}  unexpected entry in project root — only global/, lv-{n}/, mesh/, _IdMap.csv are allowed`);
  }

  // Validate project_metadata.json
  const metadataPath = join(dir, 'project_metadata.json');
  if (existsSync(metadataPath)) {
    try {
      const raw = readFileSync(metadataPath, 'utf-8');
      const metadata = JSON.parse(raw);
      if (typeof metadata !== 'object' || metadata === null || Array.isArray(metadata)) {
        issues.push('project_metadata.json  must be a JSON object');
      } else {
        const fv = metadata.format_version;
        if (fv === undefined || fv === null) {
          issues.push('project_metadata.json  missing "format_version"');
        } else {
          const n = typeof fv === 'number' ? fv : parseInt(String(fv), 10);
          if (!Number.isFinite(n)) {
            issues.push(`project_metadata.json  invalid "format_version": ${fv}`);
          } else if (n < CURRENT_FORMAT_VERSION) {
            issues.push(
              `project_metadata.json  format_version ${n} is no longer supported. Run: npx tsx scripts/svg-to-geojson.ts <project_dir>`,
            );
          } else if (n > CURRENT_FORMAT_VERSION) {
            issues.push(`project_metadata.json  format_version ${n} is newer than CLI (${CURRENT_FORMAT_VERSION})`);
          }
        }
        for (const key of Object.keys(metadata)) {
          if (!['format_version', 'project_name', 'units', 'source'].includes(key)) {
            issues.push(`project_metadata.json  unknown field "${key}"`);
          }
        }
        if (metadata.units !== undefined) {
          const validUnits = ['m', 'ft', 'in', 'mm'];
          if (typeof metadata.units !== 'string' || !validUnits.includes(metadata.units)) {
            issues.push(
              `project_metadata.json  invalid "units": ${JSON.stringify(metadata.units)} — must be one of ${validUnits.join(', ')}`,
            );
          }
        }
      }
    } catch (e) {
      issues.push(`project_metadata.json  failed to parse: ${(e as Error).message}`);
    }
  }

  return issues;
}
